### ISSUE TITLE
Feature Request: constrain the speed above some range (KiBps) and set decimal precision

### ISSUE THREAD

**Issue by aavaas** [cardsurf/download-and-upload-speed#1]
like in this applet: http://cinnamon-spices.linuxmint.com/applets/view/141

**Comment by cardsurf** [comment]
Thanks for the feedback. I will consider to add these features.

**Comment by cardsurf** [comment]
An option to set a number of decimal places has been implemented in version 1.2.0.
  In the nearest future I don't have plans to add download and upload speed restrictions.
