### ISSUE TITLE
[Feature Request] Change objects

### ISSUE THREAD

**Issue by anicetoclucas** [cardsurf/download-and-upload-speed#10]
I love your applet, but there is one thing I wanted to change and I couldn't.
I just want to change de order of Download and Upload, putting the download number down.
Can you add this?

Thank you.

**Comment by cardsurf** [comment]
I have added this feature [here](https://github.com/linuxmint/cinnamon-spices-applets/pull/2425).
You can download the new applet version from the Spices website or from the Applet window in Cinnamon.
