### ISSUE TITLE
Applet reports 2x upload / download traffic as "System Monitor"

### ISSUE THREAD

**Issue by jonathancross** [cardsurf/download-and-upload-speed#3]
I am seeing this applet indicating 2x the traffic of the Linux Mint System Monitor. See screenshot of both apps running together.
FYI: I have only 1 network interface (eth0).

![screenshot-download-and-upload-speed](https://cloud.githubusercontent.com/assets/5115470/15532204/cbbf1c68-225e-11e6-812a-0f3a3170050f.jpg)

**Comment by cardsurf** [comment]
Try to change a value of the "update every" parameter in the applet configuration to 0.5 and see if it helps.

**Comment by jonathancross** [comment]
Thanks @cardsurf. I played with the setting for a while and also similar settings in System Monitor and got them to a point where the numbers were similar: 1 second seems to work best.

I was surprised that the network traffic amounts shown were dependent on how frequently the display updates?  Seems strange to me, but feel free to close this issue if this is "expected" behavior :-)

**Comment by cardsurf** [comment]
The parameter determines how often to calculate download and upload speed.
In the next release I will add a more detailed description of the parameter and an option to apply a scaling function to download and upload speed.
I will leave the issue open until these features are implemented.

**Comment by jonathancross** [comment]
Cool, thanks.  I look forward to it.

**Comment by cardsurf** [comment]
This feature has been added in version 1.3.0.

To check that the numbers match run the applet and System Monitor on the same time interval and set the following settings in the applet configuration:
**Show**: Average speed per second
**Unit**: [Base data unit used in System Monitor]
**Calculate every**: [Update interval used in System Monitor]
