### ISSUE TITLE
Feature Request: Add a switch to select bits/s or Bytes/s

### ISSUE THREAD

**Issue by johnnyhopeful** [cardsurf/download-and-upload-speed#4]
Thanks for the great utility.

Is it possible to add a switch to the config page that allows the users to toggle the speed displayed between bits/sec and Bytes/sec?

Thanks again

**Comment by cardsurf** [comment]
Sounds like a good idea. I will add this feature in the next release.

**Comment by johnnyhopeful** [comment]
That's great news. Thanks for taking the time to incorporate the request in the next release.

**Comment by cardsurf** [comment]
This feature has been added in version 1.3.0.
