### ISSUE TITLE
Translation support

### ISSUE THREAD

**Issue by eson57** [cardsurf/download-and-upload-speed#6]
Hi,

Can you please add translation support? I could make pull request if you want to, but looking at your code, I get the feeling that you would prefer to do it yourself. 
I also have translation template.pot and Swedish translation ready for upload.

**Comment by cardsurf** [comment]
Hi,

Sure. Please upload the translation files here and I will add this feature.

**Comment by eson57** [comment]
Thanks! You need to add translation support to applet.js, appletGui.js and files.js, but you already know that.


[translationFiles.zip](https://github.com/cardsurf/download-and-upload-speed/files/908038/translationFiles.zip)

**Comment by cardsurf** [comment]
This feature has been added. The translation support is available in the "Cinnamon3_2" branch in this repostiory. I will push it to the main Cinnamon repostiory as a part of the next release.

Thanks for adding this feature.

**Comment by eson57** [comment]
Thanks! 👍

**Comment by cardsurf** [comment]
The translation support feature has been added in version 1.4.0.
