### ISSUE TITLE
Could you Create a desklet of download and upload speed?

### ISSUE THREAD

**Issue by giwhub** [cardsurf/download-and-upload-speed#7]
I want it to float on the desktop,Like this
![screenshot-area-2017-05-06-111854](https://cloud.githubusercontent.com/assets/14066437/25769512/db6afc0e-324d-11e7-9a2c-9f7479036f86.png)

**Comment by cardsurf** [comment]
Hello. I made a script that converts the applet to a desklet. To make a desklet port of the applet:
1. Install Download and upload speed applet
2. Run the [script](https://github.com/cardsurf/download-and-upload-speed/files/981447/port.sh.zip)
3. Enable the desklet in Cinnamon settings

![desklet](https://cloud.githubusercontent.com/assets/3139729/25779298/36a5c1d6-3315-11e7-9e6e-8b8a3254692a.png)

**Comment by giwhub** [comment]
Thank you very much!
